### ISSUE TITLE
Make early steel cost lower from 8 to 6 plates 

### ISSUE THREAD

**Issue by jodokus31** [KiwiHawk/SeaBlock#100]
In the past early steel cost were 4 plates.
First tier Advanced steel smelting also need 4 iron ore.
Now it was increased by Angels mods to 8 plates, so it's a nice middle way to use 6 plates to leave advanced steel better

**Comment by jodokus31** [comment]
Was overridden with #101

**Comment by KiwiHawk** [comment]
Sorry, didn't see that you had already created this!
