### ISSUE TITLE
Cargo Ships Incompatibility

### ISSUE THREAD

**Issue by zerostarm** [KiwiHawk/SeaBlock#124]
Hello,
I get the error in the image below whenever a new chunk is loaded (so on startup of new map and in a previous map when exploring new chunks). 

I have tested by having Seablock (v0.5.3), Seabloc Pack (v1.1.2) and Cargo ships (v0.0.59 and v0.0.60Seraph) (plus some other stuff that was shown to not affect this error) on together and creating a new map with default settings, the error appears immediately upon loading into the map.  

I tested that it is a Seablock - CargoShip incompatibility by removing only Seablock, and keeping on Seablock Pack and starting a new world. That world did not have the error. Also removed Cargo Ships and that got rid of the error.

Having looked at the code for Cargo Ships and Seablock I think that somehow Seablock is removing crude-oil from data.raw["resources"] before Cargo Ships is loaded in the data stage thus making it so that in prototypes.entities.oil_rig the deep copy of crude-oil "works" but only returns an empty list which then throws the error later when it tries to call the list but its just an empty list. But I'm not good enough to pinpoint where in Seablock mapgen this is  occuring exactly. I've tried putting in exceptions specifically for crude-oil and deep_oil but those didn't work 

![Seablock-CargoShips on_start_new_map error](https://user-images.githubusercontent.com/22080255/112706995-11273780-8e76-11eb-982d-8da03e7eb607.png)

**Comment by KiwiHawk** [comment]
The mod has a frequency setting for deep oil. Setting this to none seems to prevent the error occurring.

Fix:

- Force deep oil frequency setting to None
- Hide all settings related to deep oil
- Hide oil rig item
