### ISSUE TITLE
Refining recipe rebalance

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#129]
Buff crushed, chunk, crystal, purified direct sorting recipes to be situationally competitive with catalyst sorting.

For the direct sorting of crushed, chunks and crystals, decrease input quantity by 1 and remove slag from the output.

For direct sorting of purified ore, increase the last output ore by 1.

For sorting recipes, decrease output ore quantity by 1 and add slag.

**Comment by KiwiHawk** [comment]
Remove Gold and Cobalt from Chunk sorting (if Angel's haven't already).

**Comment by Pezzawinkle** [comment]
I have a feeling this won't have the intended consequences, especially considering slag is more useful in seablock, moving it to combo-sorting would only make that more competitive...

**Comment by jodokus31** [comment]
Not really, because the input/output ratio is worse for catalytic sorting compared to basic sorting:

catalytic sorting:
2+2 crushed + catalyst -> 3 same ores + 1 slag
1 slag is worth less, than an ore.

basic sorting:
3 crushed -> 3 different ores

**Comment by KiwiHawk** [comment]
New plan: Increase the slag output of all the mixed output sorting recipes from 1 to 2. Not including ferrous or cupric sorting.

This looks excellent for Crushed sorting. It's probably not enough of a buff for Chunk or Crystal sorting. These can be reviewed again at another date.

1. Mineralized water crystalization. Crushed smelting
2. Mineral sludge crystalization. Crushed smelting
3. Mineral sludge crystalization. Basic sorting. Ore smelting
4. Mineral sludge crystalization. Basic sorting. Molten smelting
5. Mineral sludge crystalization. Catalyst sorting. Molten smelting
6. Mineral sludge crystalization. Ferrous + catalyst sorting. Molten smelting

![Sorting0](https://user-images.githubusercontent.com/59639/125938435-83167785-a8fc-4f59-89d8-c2d8abc00ca2.PNG)
![Sorting1](https://user-images.githubusercontent.com/59639/125938446-8cc8955c-8bd6-40d5-ba27-8de5e1e96f7f.PNG)
