### ISSUE TITLE
Disable Nickel plates

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#156]
Remove Nickel plate from Roboport antenna array 4.
Remove Nickel plate from Roboport antenna array 3 and replace with Titanium.

Hide nickel plate and sheet coil. Disable and hide casting / strand casting recipes.

**Comment by blackerking** [comment]
I still can find the recipes in version 0.5.7.
Is that correct?
![grafik](https://user-images.githubusercontent.com/2019363/139740131-ca997154-cd6d-45a7-9fb6-af9b776bda97.png)

**Comment by KiwiHawk** [comment]
Yes, this is correct. In FNEI, any recipe with a gray title has been hidden and is cannot be used. I recommend you untick "Show Hidden Recipes" in FNEI's settings.

Keep "Show Disabled Recipes" ticked though. Disabled recipes have a red title. These are ones that you haven't researched the tech for yet.

I've asked the FNEI dev to have "Show Hidden Recipes" unticked by default but haven't heard anything back yet.
