### ISSUE TITLE
Unable to load game with just Sea Block (and dependencies) enabled - Cycle in (normal) technology tree detected

### ISSUE THREAD

**Issue by sctjkc01** [KiwiHawk/SeaBlock#158]
I am attempting to load up a game with the Sea Block pack + some others enabled, and ran into an issue.  Being a diligent bug reporter, I did my best to narrow down what's going on, and narrowed it to specifically this mod.  Not the pack as a whole, the Sea Block mod in particular.

I've enabled all of this mod's dependencies (Angel's Bioprocessing, Petrochem, Refining, Smelting + Bob's Electronics, Logistics, Plates) without Sea Block and the game loads fine... however _just_ adding Sea Block causes a crash on game load:

> Failed to load mods: Difficulty normal: Cycle in technology tree detected.
> steel-processing
> -> basic-chemistry-2
> -> water-treatment-2
> -> slag-processing-1
> -> steel-processing

I am running Factorio 1.1.35 (build 58756 - what Steam has as the `[1.1.x]` version).

**Comment by KiwiHawk** [comment]
Sea Block isn't yet compatible with the latest versions of Angel's mods. Revert these back and everything will work fine 🙂

Required mod versions are listed on the Sea Block forum post: https://forums.factorio.com/viewtopic.php?t=93136

Forum post also has a link to download a .zip of all the mods in the pack at the correct versions.

**Comment by KiwiHawk** [comment]
Fixed by #150
