### ISSUE TITLE
Review cupric chain

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#16]
Make useful / required / remove. Maybe add as an ingredient for T3 modules? Platinum?

**Comment by jodokus31** [comment]
I think the second tier with milling drums is quite interesting, because it yields 2x copper, 1x tin and 1x silicon in a good overall ratio. However, the needed lubricant is a bit of a PITA

**Comment by KiwiHawk** [comment]
#151
