### ISSUE TITLE
Error on startup with SCT

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#162]
![unknown-1.png](https://user-images.githubusercontent.com/59639/122822385-18a19400-d332-11eb-87f1-ee33702cd70e.png)

![unknown-2.png](https://user-images.githubusercontent.com/59639/122822441-2b1bcd80-d332-11eb-942a-c821c75b437f.png)

**Comment by EdBoys** [comment]
[Float On.zip](https://github.com/KiwiHawk/SeaBlock/files/6689389/Float.On.zip)

**Comment by KiwiHawk** [comment]
Reported to SCT: mexmer/ScienceCostTweakerM/issues/67
Workaround: Enable Bob's Technology mod.
