### ISSUE TITLE
Platinum smelting recipes disabled

### ISSUE THREAD

**Issue by Danacus** [KiwiHawk/SeaBlock#174]
All smelting recipes for platinum appear to be disabled in the latest main branch. The technology for platinum smelting does not exist, but "Advanced platinum casting 2" does exist.

**Comment by KiwiHawk** [comment]
Can you please upload a save file showing the issue? I can't recreate it

**Comment by Danacus** [comment]
[Seablock.1.1.zip](https://github.com/KiwiHawk/SeaBlock/files/6772071/Seablock.1.1.zip)

The save file was recently upgraded from factorio 0.18 and might even go back to 0.17 or 0.16. It also has a more mods that are not in seablock that might be the cause of the issue. If it can't be reproduced in new saves, I might have to run some lua in the console to fix it manually.

**Comment by Danacus** [comment]
I just checked and the "Advanced platinum casting 1" technology exists in new saves with my mods, but not in the save I just uploaded.

**Comment by Danacus** [comment]
I was able to fix this issue by running `/c game.get_player(1).force.technologies["angels-platinum-smelting-1"].enabled = true`.

**Comment by KiwiHawk** [comment]
You'll also want to run
```
/c game.get_player(1).force.technologies["angels-platinum-smelting-2"].enabled = true
/c game.get_player(1).force.technologies["angels-platinum-smelting-3"].enabled = true
```

**Comment by Danacus** [comment]
Thanks! I didn't notice I was missing those too.
