### ISSUE TITLE
Thorium and deuterium fuel require zinc plate

### ISSUE THREAD

**Issue by Danacus** [KiwiHawk/SeaBlock#176]
Zinc plates were removed in #157, however some recipes for nuclear fuel still use them. They should probably be replaced with something else.

**Comment by KiwiHawk** [comment]
These recipes are added by Angel's Industries. Switch Zinc plate for Lead plate.

**Comment by Danacus** [comment]
In that case it's probably not your responsibility to fix it since that mod is not officially in the SeaBlock pack. Thanks for fixing it anyway!
