### ISSUE TITLE
Hydrogen + Oxygen to purified water is very weak

### ISSUE THREAD

**Issue by brainfart123** [KiwiHawk/SeaBlock#188]
I had the idea of recombining the excessive amounts of hydrogen and oxygen slag produces and using it for filtering and electrode cleaning, thinking it would become more power efficient, but it takes more power than plain Hydroplants do, inclusive voiding of salt water, hydrogen and oxygen. Could you maybe buff the recombination recipe, so it uses less power? Buffing just the recipe until it becomes better than hydroplants might look weird because the hydroplant has very low power consumpion, which is the main reason why it is better.
Later it would not be of too much use, because you would have better uses for the hydrogen but early its a nice tweak for power efficiency.

<details>
  <summary>Here is the String for the factory planner for comparison and tweaking: </summary>
eNrtWF1v27gS/SuBnyPDdpO26VvqJrvFJkVuE+A+XCwMShpbXFOiLknF1gb57/cMSdlykt5mC2yzAfyQIJnhDM98HVK8G5Q6n92SsVJXgw+D8XA8nBwNDge0rrVxM2gtucGHu8GpNJkRc+cXvRtOsOajdk5RRdkSwtFwDDmk06Kplq3/bf3i4+GYxbBvpLsyOiNrZbXwNkdBp8tSVPmMf6a6+m9DZvaV8lNFgHCtmyq3fvVk+MavrttTa6lMob+SNX2ShjIXAgCMIeOfNsZqc1YVosqopMoFLBMPPChn0008b4YjiD+RyJXOltdOZEsgPNfmtFqQsjExR0+v+ajTbsVJWOGKS2GWSGqMkZ2f5dIB0NpRxbkOFifD8THr1rXSVt7Swdk6E7fCbYvxHurzL2efe9k6l0odXVIIduSdnyu9OkDmnNEKcoQTDFUj88vGOtbH+Mdvofhl+tvnuAF7/BWJb/lXjCOk41eNvvA1t721v13PrvSKTA/Qxc0XlK1MZSUQ4uxS52Qq+Sfl3mw05BAv4H0O4Gfw2boi1J99jnrKKyEr17XGsS/VhV7IL+SmqGO1rcQ4aqyT2Y2BFZastFkG9VvfJpdi/VU4mgqVNYqB+cQcDY84M19EpVPtA3vDSWGIVzJDzT5ppSR1G3Gy/tVA8dlReU3CZAU0k4j7K/uYHL+9kGk3O5BeZ4VQ6rRxWslqSfm0IOt6wIM+zsMvRjd1LxVBiRQ2iq6UCL37yDliriwP6GNzSWj4qbbuZkUC8Vx2O3s1iY/cvTHBRz3RFG2iyyuRLZ8yuCQnejqPpMD+WeNsIrdybyPLWlFXnjADo7BXjYAQWx8whl0sD24KBLIovOK9d3+jc51cyJC5E9SIV/taXy9lfd4obhjKMYe9yfeY/w062IDrjZHwsyzyHNOXIFgjFtQDF9Sp1PUuRb0bjt9t1DVhxLKCSq866asMzWXVGYELxycblS1Jbfr67XDst3NgkCKptCMby8HNkQpLEfMb9p3CMkmFYhozcbRHUX6NGOMgvg9C1VBtMEOJIeQ1dt0oONZw7Umz7fwHKSmQp9FVKFVfUVG5nYToA35l/aAnIZaVJQZje6WFWMnUCNP2+JOFvc7obVd22evL/BzY3b20oQemNeb7kSySVE9k6FaU9a7MUVbsSlbCzIWhnpDrPVeyjtnk2PJ4DCRch1SvySZKizwkYAKWmfQXoSK0ML5Rgz50M91SleTIhZFps+H8QN20FplLYJR2re2FOD1yykV3KjEDc5fMsVibFnkAS5r+OQ7caWzjkf9Xr5IsHBQJznjB7hJE3YXLRFiQKv2QYt+JZ++uZImVi0psth6PJ6w1oI4W8WdCUddxTJyWROrjL7eDEY4Wy+O5Erc0m8v1rnyVlGKd4MgnszB89PsMcfvHWeXsWF2JNTi9QqNbz8oJ+r2hiGvCybIuV5GXjzyP933WuDYk9S6hPalHxGAzOZeU9wpx65aJMKU22F90DRS6/k8yOpnzwYuyz/WGYO6BqElDofxU/eduUImSIVslFgcr6YqDWy1zztThQGbcDncD19a8ROL4gbRnwA6dLMmGrI+hjFTCR5nB4GT+3qbTPzDfYT8wm9MsjH5QFzJCJVY1ObgQCHvBOtPQYbe/D4i3ZGIBv+KuViJRfoeciQ+SlOc8ig+7Pz68O2agup4ptLvq3GYKZITlHdD73w8j0lmn+hxC7v6d4lyOtzw4LAWGZj2bG6IZ52YnnyvBtPiMaDYWYaCSSIU5JY2F0f/x4OvBoDkyDBXfLu4GF8jDw5x3+L2O85fJ2i96WAwuarI9exKcbwiD/xo/iSRDlAvtyXWzlFNTh5QiUbMINkiol8yvAQVWox9x7+x84mjE33NMOP6pcfsD0ftTcjwacdKzIkb4EDwjCASH0ZXuLwGea+wzU7KEXbd3uADt5PLu/lGLxFXfbBKvnmWhEUfbZZcxkHtugR8uEHjJahWI+zvxKompmbcvWaEAQX5jML6J9bUUJ5fGJX7wE0u1iL04+V6wm/tcN/uqxUXmxYq0y0MByw9H8FpK93zy7YXNEfPNqX3pWnkgOIMTvny5vwT7lRVoEynfUpKFsIletwv6Lvk9Zf501XDnsU35M6o2V7ji4yOQb4A/CP/VV69oc6P39fun1y8canVjEGAmnnPbCBYOnybOf6m/FEP6BnseLz4B+ZXNV4jAD1e8hggVTJ/TnVvrF5ssODbPuiA+Cfm1VKslxU8gK2EdJX/TaP2EYr3e0Xr8oR9r9rTH+Gow3urP/df2/VZw3T2rtP1P+u2jCpqhzdT+WWX/rLJ/Vtk/q+yfVfbPKvtnlf2zyj/lw862lSvISrsvzf7Fa/9isn8x2b+Y7F9M9i8m+9H6SS8mv9//Dxwq22Y=
</details>

**Comment by KiwiHawk** [comment]
I think I'm okay with how it is sorry. Currently there's a trade off between convenience and space efficiency vs power efficiency.
