### ISSUE TITLE
Rubber balance

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#193]
Insulated wire from rubber has been massively buffed. There's now virtually no demand for rubber.

- Disable recipe Resin > Rubber
- Remove recipe override on Red and Green wire
- Add new recipe Resin + Tinned Copper Wire > Insulated wire, unlocked by Circuit Network
- Remove I overlay from liquid rubber recipe
- Remove I overlay from rubber recipe
- Swap Insulated Wire for Rubber in Capacitor Bank recipe (Yellow Science)
- Move Wood > Resin recipe to Wood processing 3
- Make Wood processing 3 a prerequisite for Circuit Network

**Comment by jodokus31** [comment]
We could also disable resin to rubber?

**Comment by KiwiHawk** [comment]
What about wood to resin? Should that stay? Although that's getting a bit off topic. That could be disabled coupled with an overhaul of the bio resin recipes. I feel like there definitely are too many routes to resin

**Comment by jodokus31** [comment]
I don't know if bio resin got a buff. It was certainly not worth, even if you have to rush green catalyst for chemical resin. 

wood to resin is also a candidate to remove. Even if it's expensive, it encourages a shortcut to a small red circuit production.

**Comment by KiwiHawk** [comment]
Green metal catalysts are now easier too. Previously silver was the issue

**Comment by KiwiHawk** [comment]
Initial suggestion is too difficult to balance. Would need to massively increate the number of red / green wires consumed by Purple Science. More than I'm comfortable doing; the logistics would be too difficult.

New suggestion:
- Disable recipe Resin > Rubber
- Remove I overlay from liquid rubber recipe
- Remove I overlay from rubber recipe
- Add Rubber a prerequisite for Onerun Vitual Particle Forge (Yellow Science)
- Change Rubber recipe to 8x Rubber + 8x Tinned Copper Wire > 8x Insulated Wire
- Reduce Rubber recipe time down to 2s
- Leave circuit wires as they are
