### ISSUE TITLE
Check Sea Block mining compatibility

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#201]
"Is anyone using seablock-mining ? Its not enabeling mining prod research for me?"

https://discord.com/channels/546453368730681400/546478897030758431/877517201752600586

**Comment by KiwiHawk** [comment]
![image](https://user-images.githubusercontent.com/59639/129903396-322102e2-c3d4-4e18-a5ce-27df23093a1e.png)
Seems fine to me!

**Comment by Crash0** [comment]
Ok, so new game works as expected. But when i load my save, the tech is disabled. 
Is there a command i can run to enable the tech again? 
I reckon this issue is to be considered closed.
