### ISSUE TITLE
crystallizer,s Have no input and cant be rotated

### ISSUE THREAD

**Issue by lauraloldk** [KiwiHawk/SeaBlock#214]
i have all the mods, a lot stuff works fine, but the crystallizer is useless for me. there is no input for pipes, like when i watch youtubers playing the mod. + the crystallizer cant be rotated using "R" key.

**Comment by KiwiHawk** [comment]
I'm going to need more information please. Screenshots, mod list, and ideally a save game file.

**Comment by lauraloldk** [comment]
![Skærmbillede (3)](https://user-images.githubusercontent.com/6592908/133698386-706bd2d0-0cee-4632-808c-b9d2f4e899c8.png)
![Skærmbillede (4)](https://user-images.githubusercontent.com/6592908/133698434-1bffc1d4-4ca7-45c1-8024-4dc8f3d2deec.png)
![Skærmbillede (5)](https://user-images.githubusercontent.com/6592908/133698504-59f448c4-00fd-4189-acbe-dff181538a72.png)
![Skærmbillede (9)](https://user-images.githubusercontent.com/6592908/133698695-11b60957-f784-454a-877a-378cd8ab443e.png)

**Comment by KiwiHawk** [comment]
Can you pick a recipe in the crystallizer? The fluid input will show and it can be rotated once a recipe is selected.
![image](https://user-images.githubusercontent.com/59639/133708657-b79c4966-e04e-4256-9cf3-80a505554680.png)
![image](https://user-images.githubusercontent.com/59639/133708700-f8384c60-d997-436e-866e-8a3e98873a36.png)


The minimap looks very wrong. I'm guessing that you picked map type Island? This isn't supported sorry. I'd recommend restarting using the Normal map type!
![image](https://user-images.githubusercontent.com/59639/133707690-6cda87d1-0536-4fd8-96c7-45280fc1f7ce.png)

Other than Cliffs, none of the other settings on the Terrain have any effect. They can't be hidden unfortunately.

### Mod List
Also, you don't have the full mod pack.

Extra mods, not in the pack:
- Angel's Addons - C.A.B
- Angel's Addons - Mas Transit
- Angel's Industries
- Angel's Infinite Ores
- AngelBob
- Bob's Greenhouse mod
- Bob's Vehicle equipment mod
- Loader Redux

Pack mods not enabled:
- Artisanal Reskins: Angel's Mods
- Artisanal Reskins: Bob's Mods
- Artisanal Reskins: Compatibility
- Artisanal Reskins: Library
- Circuit Processing
- Explosive Excavation
- FNEI
- Helmod
- Sea Block Pack

[Sea Block Pack](https://mods.factorio.com/mod/SeaBlockMetaPack) mod does nothing on it's own. It just has dependencies on all mods in the default pack.

While it is generally fine to add or remove mods from the pack as you prefer, it's good to start from the default. If you are adding extra mods, you should know why you're adding them. Angel's Infinite Ores and Bob's Greenhouse mod particularly shouldn't be enabled.

**Comment by lauraloldk** [comment]
i did select a recipe from that machine. and i just installed the pack. the first thing i did when i started a new game was crafting a crystallizer and try to build it. again it cant be rotated, and it shows no input for pipes.

**Comment by lauraloldk** [comment]
Never mind. it works now.
