### ISSUE TITLE
Error while creating headless server

### ISSUE THREAD

**Issue by blackerking** [KiwiHawk/SeaBlock#229]
It seems not possible to create a new map with the standard and required mods

`0.000 Error Util.cpp:83: "coal" is not a valid autoplace control name.`

While searching I came across this issue:
[https://github.com/factoriotools/factorio-docker/issues/114](https://github.com/factoriotools/factorio-docker/issues/114)

**Comment by blackerking** [comment]
I am not sure what for changes I have to make.
Did I have to set everything to 0 or delete the whole line?

**Comment by KiwiHawk** [comment]
Like this:
```
"autoplace_controls":
    {
      "enemy-base": {"frequency": "normal", "size": "normal", "richness": "normal"}
    },
```

**Comment by KiwiHawk** [comment]
I've added the info the the Sea Block FAQ page. https://mods.factorio.com/mod/SeaBlock/faq
