### ISSUE TITLE
Startup warning

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#23]
I'm seeing a great deal of this on startup:  20.451 Script @angelspetrochem/prototypes/petrochem-global-override.lua:13: Recipe 'angelsore9-sludge' does not have a crafting_machine_tint set!

Investigate if this is important

**Comment by LovelySanta** [comment]
it's not important, this is 100% angels doing, but until kira finishes HQ buildings for petrochem, this will be on hold, the chem plant is supposed to have some crafting tints...
