### ISSUE TITLE
Techs that require blue science packs to research should require blue research packs to be unlocked.

### ISSUE THREAD

**Issue by theunkn0wn1** [KiwiHawk/SeaBlock#237]
There is a large collection of dependencies, such as `Inserter Capacity Bonus 2`, `Lab Research Speed 3`, `Chlorine Processing 3`, `Sulfur Processing 4`, etc. that are part of the base Seablock pack that  require blue science packs to research, that do not require the player to have first researched `Uni-lived atomic manipulator` (blue science tech unlock) to initiate research. This is illogical, these techs should not be listed as available to research, given its impossible to research them by normal means at this point. 

Expected behavior: any tech that requires blue science packs as a research ingreedient should have `Uni-lived Atomic Manipulator` tech listed as a prerequisite. 

Current behavior: Most techs are consistent with expected behavior, however there are some outliers in the seablock pack which do not. Some techs can be initiated in a state where no progress can be made (As blue science packs cannot be made yet.)
![image](https://user-images.githubusercontent.com/3110986/143155873-7f20dc19-55de-421e-a393-9220bd83a583.png)

**Comment by KiwiHawk** [comment]
**Exception:**
Any upgrade tech >1 should only depend on the previous tier of upgrade.
This matches base game and helps keep the tech tree from become too cluttered.
For example, Inserter Capacity and Lab Research Speed are correct in this screenshot. Chlorine Processing and Sulfur Processing are missing a prerequisite.

This may have already been fixed. If not, check why it wasn't picked up by the unit test.
