### ISSUE TITLE
Buff thermal-bore-water recipe

### ISSUE THREAD

**Issue by PeterMeisrimel** [KiwiHawk/SeaBlock#241]
The "thermal-bore-water" recipe values seem off. I suppose this should give 50 instead of 5 thermal water.

**Comment by KiwiHawk** [comment]
I'm not sure if this is a bug or not.

I feel that changing the thermal water bore recipe from give 5 thermal water to 50 would be too much of a buff. It would then have the same ratio of brown algae : thermal water as the extractor.

However I do think there's scope to buff the bore without making the extractor obsolete. Maybe changing it's output from 5 to 20.
