### ISSUE TITLE
Lithium processing can't be researched in seablock 0.5.9

### ISSUE THREAD

**Issue by tornewuff** [KiwiHawk/SeaBlock#246]
With the seablock 0.5.9 pack the `lithium-processing` tech has a prerequisite of `chemical-processing-1` which is disabled and hidden. Seablock 0.5.8 used to replace this dependency with `sb-chlorine-processing-4` but it was removed in 5eefbaf979669e and the code in Angels that sets up the dependency on `chlorine-processing-4` does not remove `chemical-processing-1`.

**Comment by KiwiHawk** [comment]
Also reported on mod portal: https://mods.factorio.com/mod/SeaBlock/discussion/61bfc0c32d1def68baa3924d
