### ISSUE TITLE
Angels Industries: Advanced deuterium fuel reprocessing

### ISSUE THREAD

**Issue by Danacus** [KiwiHawk/SeaBlock#276]
Angels Industries adds this recipe to reprocess deuterium fuel cells without losing catalysts. However, this is disabled if components mode is turned off, which is the case in SeaBlock. I believe this is done intentionally, because there is no good way to get rid of excess catalysts.

As a result, you have to use thorium reactors and thorium fuel cell reprocessing to get some catalysts to compensate for the minor loss of muon fusion catalysts in the basic fuel reprocessing recipe. 

I wonder if it would make more sense to enable advanced deuterium fuel reprocessing anyway, such that you don't need thorium reactors to keep deuterium reactors running.

**Comment by KiwiHawk** [comment]
Angel's nuclear overhaul was deliberately designed so you have to keep running earlier tiers to feed the higher tiers. So it's working as intended.

Angel's Industries isn't part of the default Sea Block mod pack. I try keep it compatible. But I'm not going to be making big changes to it.
