### ISSUE TITLE
Small artifact crafting disabled

### ISSUE THREAD

**Issue by carlbarfuss** [KiwiHawk/SeaBlock#278]
- Regular seablock modpack installed
- Can craft the different pastes, but recipes for small and large artifacts are disabled
[Seablock for KiwiHawk.zip](https://github.com/KiwiHawk/SeaBlock/files/9522060/Seablock.for.KiwiHawk.zip)

**Comment by carlbarfuss** [comment]
disabling and reenabling bob's enemies AND angel's bioprocessing fixes the issue, at the cost of removing all of the associated items and recipe progress from the game.

**Comment by KiwiHawk** [comment]
Fixed by #285
