### ISSUE TITLE
Remove Chemical and Metal mixing furnaces

### ISSUE THREAD

**Issue by Dimava** [KiwiHawk/SeaBlock#28]
Currently there is only 1 recipe for Chemical furnace
 - Silicon nitride (Silicon powder, Nitrogen gas)

and 5 recipes for Metal mixing furnace
 - Tungsten carbide plate I (Tungsten oxide, Carbon)
 - Tungsten carbide plate II (Tungsten powder, Carbon)
 - Copper-tungsten plate (Tungsten powder, Copper plate)
 - Blue alien alloy (Tungsten plate, Blue alien artifact)
 - Orange alien alloy (Tungsten plate, Orange alien artifact)

It is safe to move them all to Blast Furnace and delete Chemical and Metal mixing furnace chain completely

Fluid burning furnaces may also be deleted or set under mod setting

**Comment by KiwiHawk** [comment]
Will wait to see if Angel's implements this first.

If I did make this change, the chemical furnace recipe would be moved to Angel's Chemical Furnace. The Metal mixing furnace recipes would be moved to the Sintering Oven. Tech prerequisites for this look fine to me.

**Comment by KiwiHawk** [comment]
Chemical furnace has 3 recipes:
- Silicon nitride
- Silicon carbide
- Lithium cobalt oxide

**Comment by KiwiHawk** [comment]
- Removed Bob's Chemical furnaces. Recipes moved to Angel's Chemical furnaces
- Metal mixing furnace recipes moved to Sintering oven or Blast furnace
- Stone metal mixing furnaces are available at the start of the game
- Bob's assembling machines mod setting Fluid burning furnaces defaults to false
