### ISSUE TITLE
Sour gas possibly not marked as hidden

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#38]
What's up with sour gas, YAFC seemed to think it's accessible and that oil techs seem to unlock recipes related to it.
Seem to be accessible in editor too, though the actual recipes aren't given on the techs themselves.

Not sure if this is a Sea Block problem or YAFC problem.

**Comment by Black-Noise** [comment]
This has been fixed on the yafc side by setting hidden techs as inaccessible, see: [https://github.com/ShadowTheAge/yafc/issues/86](url)
