### ISSUE TITLE
Reduce techs that depend on Sacrificial electromagnet

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#39]
Without SCT enabled, the only techs that depend on lab tech are:
- Basic logistics
- Optics
- Automation
- Gun turret
- Stone wall
- Wood processing 2
- Military

![image](https://user-images.githubusercontent.com/59639/102875821-325c3e80-44a9-11eb-9c82-ead39427baa1.png)

**Comment by KiwiHawk** [comment]
Commented out line in ScienceCostTweakerM\prototypes\2_technology:
--connect_sciencepack(nil, first_science)

![image](https://user-images.githubusercontent.com/59639/102957058-5453d080-453e-11eb-804f-86f221890937.png)

**Comment by KiwiHawk** [comment]
Looks like it's a SCT bug

mexmer/ScienceCostTweakerM#54

**Comment by KiwiHawk** [comment]
Calling bob function to clean these up is good enough workaround for now.

**Comment by mexmer** [comment]
@KiwiHawk it's not bug, it's a feature, and mod has setting for it.

**Comment by mexmer** [comment]
![image](https://user-images.githubusercontent.com/5429727/103215435-9b154200-4913-11eb-8644-ff51f245e0bd.png)

**Comment by mexmer** [comment]
if you look at seablockconfig mod, trainwreck was altering some of my mod settings trough it, i believe, he also disabled this one.
