### ISSUE TITLE
Hide most military stuff

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#4]
Remove:

- Landmines
- Robotic attack drones
- Extra artillery shell types
- Glycerol, Nitroglycerin, Toluene
- Alien science
- Infinite damage upgrade techs
- Capsules
- Discharge defence
- Gunmetal
- Armoured trains
- Other military stuff not mentioned below

Keep:

- Light, Heavy, Modular armour
- Power armour (all)
- Personal equipment
- Walls, gates (people use them for aesthetics and safe rail crossings)
- Basic & piercing magazines
- Pistol, Submachine gun, Sniper rifle, Rocket launcher
- Rocket, Atomic bomb
- Grenade
- Gun turret 1, 2
- Sniper turret 1, 2
- Alien artifacts
- Plasma turret 1, 2
- Artillery (all)
- Car, Tank
- Cannon shell, Explosive cannon shell
- Spidertron and variants
- Powerups
  - Physical projectile damage 1 - 6
  - Energy weapon damage 1 - 6
  - Stronger explosives 1 - 6
  - Shooting speed 1 - 6
  - Artillery shell range
  - Artillery speed

Other:

- Make sniper rifle available earlier (pre blue science)
- Remove "I" overlay from Explosives recipe
- Replace Glycerol with Water in Nutrient Pulp recipe
- Replace alien tech other science packs:
  - Battery 4 - 6
  - Shields 4 - 6
  - Power armour 3 - 5
  - Fusion reactor 2 - 4

**Comment by KiwiHawk** [comment]
Needs to be a setting for this. If / when I a add a Land Block mode, these other military techs & recipes may be useful.

**Comment by jodokus31** [comment]
I would add tanks to keep list? They are quite useful
And gunmetal can be removed, too (Or used elsewhere, maybe in mil science instead of brass or invar)

**Comment by KiwiHawk** [comment]
Need to override nutrient pulp > fuel oil + water recipe icon (with AR)

**Comment by KiwiHawk** [comment]
Without Bob's Warfare, laser turret is an ingredient in personal laser defence
