### ISSUE TITLE
Angel's Industries Support

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#59]
Keep Requester / Provider chests as yellow science.

Disable component mode and science mode settings.

**Comment by KiwiHawk** [comment]
Do we actually need to disable components mode? 🤔 Would need to fix the basic circuit board tutorial tech.

**Comment by Pezzawinkle** [comment]
id force it off if I were you, at least until it is more stabilized on our end, and you get enough "want"

**Comment by Pezzawinkle** [comment]
```
if angelsmods.industries.components then
  add_con_mats()
  OV.execute()

  replace_gen_mats()
  OV.execute()
end
```
this is the call to replace blocks and general materials for component mode
