### ISSUE TITLE
ick's Sea Block Pack

### ISSUE THREAD

**Issue by ickputzdirwech** [KiwiHawk/SeaBlock#60]
Hey, I just wanted to let you know that I am currently working on a custom version of the Sea Block Pack called [ick's Sea Block Pack](https://github.com/ickputzdirwech/SeaBlockCustomPack).
 
My aim is to tidy everything up as much as possible on the default settings. I didn't take different mod settings or sets of mods into account. Most of the changes are hiding unnecessary stuff and reordering even more stuff. I did some small changes including to dependencies and settings that maybe wouldn't fit in the original mod. I noticed that you are working on some similar issues.  If you get inspired feel free to take anything from it that you want.  I don't understand the structure of the Sea Bock mod and which sets of mods and settings should be supported, otherwise I would have made some pull requests.

**Comment by KiwiHawk** [comment]
I'll take a look at your changes. I have similar goals for the main mod pack. I can see I've already made some of the changes that you have on your list.

If you have any questions about structure or coding, just ask! Either here or on Discord.

**Comment by ickputzdirwech** [comment]
My first question would be: What sets of mods should be supported? I am guessing that you are trying to break as little as possible in case players add additional mods. I gathered from the dependency differences between SeaBlock and SeaBlockPack that the following mods should be safe to remove:

- angelsaddons-storage
- bobassembly
- bobenemies
- bobequipment
- bobmining
- bobmodules
- bobores
- bobpower
- bobrevamp
- bobtech
- bobwarfare
- CircuitProcessing
- Explosive Excavation
- FNEI
- KS_Power
- LandfillPainting
- ScienceCostTweakerM and
- SpaceMod

Which is a significant chunk of the modpack.

**Comment by KiwiHawk** [comment]
Anything that isn't listed as a required in Sea Block should be safe to remove. Optional dependencies in the Sea Block mod are purely functional - they are listed to ensure that Sea Block is loaded after them. There's code that reacts to the other mods being enabled.

Players should be able to remove any of the non required mods in the pack. As much as possible it should work if they add extra mods too. I don't expect it to work if someone added a major overhaul mod.

**Comment by KiwiHawk** [comment]
@ickputzdirwech I'm going to close this issue now. If you have changes that you think I should make, comment and I can reopen this.
