### ISSUE TITLE
Hide stuff

### ISSUE THREAD

**Issue by KiwiHawk** [KiwiHawk/SeaBlock#69]
Bob's electrolyser was visible in the "made in" tooltip. Mining drills and pumpjacks were visible in the bonus gui. Pollution modules and lithia water were visible in the items gui (modules and water treatment tabs). Mining recipes are visible in FNEI and Factory Planner.

**Comment by ickputzdirwech** [comment]
Iron rod and iron rod stack are visible in the item gui (metallurgy casting tab),.

**Comment by Pezzawinkle** [comment]
Good point on the electrolysers... i would hold off on these until i get my hidden stuff branch done in angels published...
I have up-to industries (excluded) done, just need to quickly add the buildings and then hit industries... after that i can ensure that the updated function (which should be published in the next refining update) will hide any recipe which is disabled using the `angelsmods.ov_functions.disable_recipe()` function. Alternatively, there is a relatively new function which can be used in isolation called `angelsmods.ov_functions.hide_recipe()`

**Comment by KiwiHawk** [comment]
Pollution boards are handled by Circuit Processing KiwiHawk/CircuitProcessing#7
I've done the mining productivity by removing all effects from the mining productivity techs before hiding them.

Thanks, yes - I've seen lots of recipes which should be hidden but aren't. I'll look again once I've got the Refining update.

**Comment by ickputzdirwech** [comment]
> I've done the mining productivity by removing all effects from the mining productivity techs before hiding them.

I am not sure this is really the ideal solution. Because it won't work with Seablock Mining. I've done it by setting the flag "hidden" to the entities (pumpjack, burner- and electric-mining-drill). I don't think it's necessary in this case but you might have to remove next_upgrade from the entity too, since it can conflict with the "hidden" flag. For a more general approach you can always iterate over data.raw["mining-drill"] to get all mining drills.

**Comment by KiwiHawk** [comment]
If Sea Block Mining is installed, I don't touch the productivity techs at all. I tried setting thee hidden flag but they still show in the bonuses screen. I checked and next_upgrade is already nil for all three.

I don't see this as an actual issue as it only shows up in Sandbox or if something like Creative Mod is used to unlock all techs.
