### ISSUE TITLE
MadClowns Support options

### ISSUE THREAD

**Issue by Pezzawinkle** [KiwiHawk/SeaBlock#73]
This may be a tad complex (as with all modular packs):
MadClowns Processing:
 * Adds materials and is essentially a smelting/petrochem extension

MadClowns Extended Materials:
 * clowns-ore# (1-9 for raw ores)  --these are essentially like angels ores
 * IF PURE ANGELS (special vanilla mode only get ore1,4,5,7)
 * clowns-resource# (special vanilla only gives 2, with both 1 and 2 active without) --these are essentially like oil patches but use regular miners

The processing of these unlock directly after angels ones in the tech tree... 
resource1 unlocks in "water-washing-2", while resource2 processing unlocks with "oil-gas-extraction".

Clowns nuclear (both) go into mostly hybernation with angels industry active but don't generally impact ore generation stuff.

**Comment by KiwiHawk** [comment]
![image](https://user-images.githubusercontent.com/59639/104835380-1c586700-590b-11eb-9657-712651d6d3c0.png)
![image](https://user-images.githubusercontent.com/59639/104835403-3b56f900-590b-11eb-93d3-8ca935a9d68d.png)
![image](https://user-images.githubusercontent.com/59639/104835378-12366880-590b-11eb-8c05-658ceebdb20c.png)
![image](https://user-images.githubusercontent.com/59639/104835392-2d08dd00-590b-11eb-9543-1946011527e3.png)
![image](https://user-images.githubusercontent.com/59639/104835414-575a9a80-590b-11eb-9f8d-23365fba91bf.png)

All Helmod plans done with basic (non burner) machines.
