### ISSUE TITLE
Add a remote interface to allow other mods to set/add/remove global.unlocks and global.starting_items

### ISSUE THREAD

**Issue by Cereal-Sam** [KiwiHawk/SeaBlock#75]
SeaBlock´s global unlock table that has the information about which item unlocks which startup tech can currently not be modified by other mods.

I can add my own unlock code ofc, but i have currently no way of stopping SeaBlock from unlocking techs i dont want to be unlocked.

An easy implementation could look like this.
```lua
remote.add_interface(
    "SeaBlock",
    {
        setUnlocks =
        function(item, unlocks)
          global.unlocks[item] = unlocks
        end
    }
)
```

Using add/remove functions instead of a setter would give you probably more control over what can be done tho.

**Comment by KiwiHawk** [comment]
Interface name:
SeaBlock

Functions:
get_unlocks() returns table of string, table of string. { [item name] = {tech name 1, tech name 2}, … }
get_starting_items() returns table of string, integer. { [item name] = quantity, … }
set_unlock( item: string, techs: table of string )
set_starting_item( item: string, quantity: integer )

Set methods can be used to remove by passing nil as second parameter.

Mods modifying these should also modify table data.script_enabled. This table is populated by Sea Block in data stage. Read by YAFC, potentially other mods when calculating which recipes are accessible.

data.script_enabled = {
  { type = 'item', name = <item name> },
  { type = 'technology', name = <technology name> }
}

**Comment by KiwiHawk** [comment]
Wiki doc: https://seablock.fandom.com/wiki/Remote_Interface
